export default {
    FETCH_FLIGHTS: 'FETCH_FLIGHTS',
    FETCH_FLIGHTS_SUCCESS: 'FETCH_FLIGHTS_SUCCESS',
  
    FETCH_START: 'FETCH_START',
    FETCH_END: 'FETCH_END',
    FETCH_API_FAIL: 'FETCH_API_FAIL',
  
    FILTER_FLIGHTS: 'FILTER_FLIGHTS',
    FILTER_PRICE_RANGE: 'FILTER_PRICE_RANGE',
  
  };
  